name: TSC
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install tsc
      run: yarn

    - name: Run ESLint
      run: tsc --noEmit
